### PR TITLE
leezy:pheanstalk:flush-tube upgraded to support job state

### PR DESCRIPTION
**Pull request by radutopala**

### CODE REVIEW

**Comment by radutopala** [comment]
@armetiz can you please look into this PR? thanks

**Comment by armetiz** [comment]
Hi @radutopala, sorry I forget to take care of it.

Can you clean commits ? There is many useless noised ... The only useful part is the one from `FlushTubeCommand `.

Can you rename the FlushTubeCommand::states const to FlushTubeCommand::allowedPeekableStates which is more explicit.

Last thing,
Can you create a dedicated methods : `flushTubeWithState($state)` ? And instead of a foreach loop, a more explicit operation like 

Something like :
```php
// $flushJobWithStateName has been checked

if($flushJobWithStateName) {
  $this->flushTubeWithState($flushJobWithStateName);
}
else {
  $this->flushTubeWithState('ready');
  $this->flushTubeWithState('buried');
  $this->flushTubeWithState('delayed');
}
```

The option is very cool ;)

Regards;
Thomas.

**Comment by radutopala** [comment]
@armetiz Ok .. I would reuse `$allowedPeekableStates` in the `} else {`, which is  DRYier, like: 
```
if ($stateName) {
    $this->flushTubeWithState($stateName);
} else {
    foreach ($this->allowedPeekableStates as $stateName) {
        $this->flushTubeWithState($stateName);    
    }
}
```
what do you think?

**Comment by armetiz** [comment]
Hi there.
I'm sorry, I totally forget about this PR.

Why the Listener::onCommand has been changed ?
Can you update your branch from master ? 

Regards.

**Comment by armetiz** [comment]
Too old.

**Pull request closed without merging**
