### PR TITLE
Make usage of TreeBuilder Symfony 5 compatible

### LINKED ISSUE #79: Tree builder without a root node deprecation
A depecrated message is raised about the configuration of the leezy_pheanstalk node. From Symfony 5 this configuration is no longer possible. Do you plan to make any improvements?
Thank you in advance

### PR DESCRIPTION
**Pull request by dontub**
Fixes #79.

### CODE REVIEW

**Comment by edmundofuentes** [comment]
I can also confirm that the current version of the Bundle breaks in Symfony 4.4.11, and that @dontub PR's fixes the issue.

**Comment by armetiz** [comment]
thank you ;)

**Comment by armetiz** [comment]
Is this bundle compatible with Symfony 5?

**Comment by edmundofuentes** [comment]
Thanks @armetiz! Would it be possible to create a new tag/release 4.0.1 in order for Composer/Packagist to auto-update it?


As for Symfony5, I set up a blank Symfony 5.1.3 to test the bundle, but I could install it directly:

```
leezy/pheanstalk-bundle dev-master requires symfony/framework-bundle ~2.5|~3.0|^4.0 -> no matching package found.
```

However, I forced-loaded it into Symfony and I think some interface has changed regarding the DataCollector, here's the stack trace:

```
PHP Fatal error:  Declaration of Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in /Users/mundofr/GitHub/edmundofuentes/symfony5test/vendor/leezy/pheanstalk-bundle/src/DataCollector/PheanstalkDataCollector.php on line 179

Fatal error: Declaration of Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) in /Users/mundofr/GitHub/edmundofuentes/symfony5test/vendor/leezy/pheanstalk-bundle/src/DataCollector/PheanstalkDataCollector.php on line 179
Symfony\Component\ErrorHandler\Error\FatalError^ {#2429
  -error: array:4 [
    "type" => 64
    "message" => "Declaration of Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL)"
    "file" => "/Users/mundofr/GitHub/edmundofuentes/symfony5test/vendor/leezy/pheanstalk-bundle/src/DataCollector/PheanstalkDataCollector.php"
    "line" => 179
  ]
  #message: "Compile Error: Declaration of Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL) must be compatible with Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL)"
  #code: 0
  #file: "./vendor/leezy/pheanstalk-bundle/src/DataCollector/PheanstalkDataCollector.php"
  #line: 179
}
```

Changing from `\Exception` to `\Throwable` in `Leezy\PheanstalkBundle\DataCollector\PheanstalkDataCollector::collect()` appears to work, but then:

```
In PutCommand.php line 21:
                                                             
  Class 'Pheanstalk\Contract\PheanstalkInterface' not found
```

And that's as far as I got, I will fork the bundle later today and try to make it work, but I'm not certain that it will be backwards compatible.

**Comment by armetiz** [comment]
Thank you for your job.

I've just released 4.0.1.

If you have to drop Symfony@~2.5 to support Symfony@^5.0, you could do it.

Regards.

**Pull request merged**
