### PR TITLE
Add symfony 4 compatibility

### PR DESCRIPTION
**Pull request by nmarniesse**
- update composer for symfony4 dependencies
- update phpunit dependencies for php7 compatibility
- set service public according to [this](https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default)

phpunit tests are passing :white_check_mark:

### CODE REVIEW

**Comment by armetiz** [comment]
Hi @nmarniesse 
Thanks for your PR !

Could you update `.travis.yml` to check this bundle with Symfony 4.* ?

When tests OK; could you please rebase your commits to a single commit?

Regards;
Thomas.

**Comment by armetiz** [comment]
Hi @nmarniesse , any news ?

**Comment by nmarniesse** [comment]
Hi @armetiz  

I add symfony4 in travis. As this version requires php 7.1.3 only, I had to add this php version too.  
All commits are rebased to a single one as you wish.

Thanks!  
Regards  

Nicolas

**Comment by armetiz** [comment]
Thanks a lot!

Regards;

**Comment by msvrtan** [comment]
Hey @armetiz, any chance of new release of the bundle for us wishing to upgrade to Symfony 4 (I'm not a big fan of depending on dev-master)

**Comment by armetiz** [comment]
Sorry @msvrtan 
I simply forgot to tag new version ;)

https://github.com/armetiz/LeezyPheanstalkBundle/tree/3.3.0

**Comment by msvrtan** [comment]
No problem at all, thank you for all the great work on this bundle!

**Pull request merged**
